/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _geosearch;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.io.*;  
import java.net.MalformedURLException;  
import java.net.URL; 

/**
 *
 * @author luyimeng
 */
public class Frame_Tenji2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Tenji2
     */
    public Frame_Tenji2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setText(Frame_Nyuryoku2.getResultNewPlaceName());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {Frame_Nyuryoku2.getNameTrans(0), Frame_Nyuryoku2.getTimeTrans(0),Frame_Nyuryoku2.getFloatLong(0) , Frame_Nyuryoku2.getFloatLat(0), Frame_Nyuryoku2.getTextTrans(0)},
                {Frame_Nyuryoku2.getNameTrans(1), Frame_Nyuryoku2.getTimeTrans(1),Frame_Nyuryoku2.getFloatLong(1) , Frame_Nyuryoku2.getFloatLat(1), Frame_Nyuryoku2.getTextTrans(1)},
                {Frame_Nyuryoku2.getNameTrans(2), Frame_Nyuryoku2.getTimeTrans(2),Frame_Nyuryoku2.getFloatLong(2) , Frame_Nyuryoku2.getFloatLat(2), Frame_Nyuryoku2.getTextTrans(2)},
                {Frame_Nyuryoku2.getNameTrans(3), Frame_Nyuryoku2.getTimeTrans(3),Frame_Nyuryoku2.getFloatLong(3) , Frame_Nyuryoku2.getFloatLat(3), Frame_Nyuryoku2.getTextTrans(3)},
                {Frame_Nyuryoku2.getNameTrans(4), Frame_Nyuryoku2.getTimeTrans(4),Frame_Nyuryoku2.getFloatLong(4) , Frame_Nyuryoku2.getFloatLat(4), Frame_Nyuryoku2.getTextTrans(4)},
                {Frame_Nyuryoku2.getNameTrans(5), Frame_Nyuryoku2.getTimeTrans(5),Frame_Nyuryoku2.getFloatLong(5) , Frame_Nyuryoku2.getFloatLat(5), Frame_Nyuryoku2.getTextTrans(5)},
                {Frame_Nyuryoku2.getNameTrans(6), Frame_Nyuryoku2.getTimeTrans(6),Frame_Nyuryoku2.getFloatLong(6) , Frame_Nyuryoku2.getFloatLat(6), Frame_Nyuryoku2.getTextTrans(6)},
                {Frame_Nyuryoku2.getNameTrans(7), Frame_Nyuryoku2.getTimeTrans(7),Frame_Nyuryoku2.getFloatLong(7) , Frame_Nyuryoku2.getFloatLat(7), Frame_Nyuryoku2.getTextTrans(7)},
                {Frame_Nyuryoku2.getNameTrans(8), Frame_Nyuryoku2.getTimeTrans(8),Frame_Nyuryoku2.getFloatLong(8) , Frame_Nyuryoku2.getFloatLat(8), Frame_Nyuryoku2.getTextTrans(8)},
                {Frame_Nyuryoku2.getNameTrans(9), Frame_Nyuryoku2.getTimeTrans(9),Frame_Nyuryoku2.getFloatLong(9) , Frame_Nyuryoku2.getFloatLat(9), Frame_Nyuryoku2.getTextTrans(9)},
                {Frame_Nyuryoku2.getNameTrans(10), Frame_Nyuryoku2.getTimeTrans(10),Frame_Nyuryoku2.getFloatLong(10) , Frame_Nyuryoku2.getFloatLat(10), Frame_Nyuryoku2.getTextTrans(10)},
                {Frame_Nyuryoku2.getNameTrans(11), Frame_Nyuryoku2.getTimeTrans(11),Frame_Nyuryoku2.getFloatLong(11) , Frame_Nyuryoku2.getFloatLat(11), Frame_Nyuryoku2.getTextTrans(11)},
                {Frame_Nyuryoku2.getNameTrans(12), Frame_Nyuryoku2.getTimeTrans(12),Frame_Nyuryoku2.getFloatLong(12) , Frame_Nyuryoku2.getFloatLat(12), Frame_Nyuryoku2.getTextTrans(12)},
                {Frame_Nyuryoku2.getNameTrans(13), Frame_Nyuryoku2.getTimeTrans(13),Frame_Nyuryoku2.getFloatLong(13) , Frame_Nyuryoku2.getFloatLat(13), Frame_Nyuryoku2.getTextTrans(13)},
                {Frame_Nyuryoku2.getNameTrans(14), Frame_Nyuryoku2.getTimeTrans(14),Frame_Nyuryoku2.getFloatLong(14) , Frame_Nyuryoku2.getFloatLat(14), Frame_Nyuryoku2.getTextTrans(14)},
                {Frame_Nyuryoku2.getNameTrans(15), Frame_Nyuryoku2.getTimeTrans(15),Frame_Nyuryoku2.getFloatLong(15) , Frame_Nyuryoku2.getFloatLat(15), Frame_Nyuryoku2.getTextTrans(15)},
                {Frame_Nyuryoku2.getNameTrans(16), Frame_Nyuryoku2.getTimeTrans(16),Frame_Nyuryoku2.getFloatLong(16) , Frame_Nyuryoku2.getFloatLat(16), Frame_Nyuryoku2.getTextTrans(16)},
                {Frame_Nyuryoku2.getNameTrans(17), Frame_Nyuryoku2.getTimeTrans(17),Frame_Nyuryoku2.getFloatLong(17) , Frame_Nyuryoku2.getFloatLat(17), Frame_Nyuryoku2.getTextTrans(17)},
                {Frame_Nyuryoku2.getNameTrans(18), Frame_Nyuryoku2.getTimeTrans(18),Frame_Nyuryoku2.getFloatLong(18) , Frame_Nyuryoku2.getFloatLat(18), Frame_Nyuryoku2.getTextTrans(18)},
                {Frame_Nyuryoku2.getNameTrans(19), Frame_Nyuryoku2.getTimeTrans(19),Frame_Nyuryoku2.getFloatLong(19) , Frame_Nyuryoku2.getFloatLat(19), Frame_Nyuryoku2.getTextTrans(19)}
            },
            new String [] {
                "用户名", "发布时间", "经度", "纬度", "内容"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("jLabel2");
        String imgurl = MapDraw.getMapURL();
        URL url = null;
        try{
            url = new URL(imgurl);
        }catch (MalformedURLException e2) {
            e2.printStackTrace();
        }
        InputStream is = null;
        try {
            is = url.openStream();
        } catch (IOException e1) {
            e1.printStackTrace();
        }
        OutputStream os = null;
        File f = new File("img3.png");
        //f.mkdirs();
        try{
            os = new FileOutputStream(f);
            int bytesRead = 0;
            byte[] buffer = new byte[8192];
            while((bytesRead = is.read(buffer,0,8192))!=-1){
                os.write(buffer,0,bytesRead);
            }
        }catch(FileNotFoundException e){
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("FINISH");
        try{
            ImageIcon icon = new ImageIcon("img3.png");
            jLabel2 = new JLabel(icon);
        }catch (Exception e){
            System.out.println("catch住");
            ImageIcon icon = new ImageIcon("Atlas_Logo_AW.png");
            jLabel2 = new JLabel(icon);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 915, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Tenji2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
