/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _geosearch;

import static java.lang.Float.parseFloat;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import weibo4j.model.WeiboException;

/**
 *
 * @author luyimeng
 */
public class Frame_Nyuryoku2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Nyuryoku2
     */
    public Frame_Nyuryoku2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("经度");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("纬度");

        jButton1.setText("确定");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(jTextField1)))
                .addContainerGap(242, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jButton1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    static Vector<String> RealName2 = new Vector<>();
    
    public static String getNameTrans(int i){
        return RealName2.get(i);
    }
    static Vector<String> RealTime2 = new Vector<>();
    public static String getTimeTrans(int i){
        return RealTime2.get(i);
    }
    static Vector<String> RealText2 = new Vector<>();
    public static String getTextTrans(int i){
        return RealText2.get(i);
    }
    static String ResultNewPlaceName;
    public static String getResultNewPlaceName(){
        return ResultNewPlaceName;
    }
    static Vector<String> FloatLong2 = new Vector<>();
    static Vector<String> FloatLat2 = new Vector<>();
    public static String getFloatLong(int i){
        return FloatLong2.get(i);
    }
    public static String getFloatLat(int i){
        return FloatLat2.get(i);
    }
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        String Longtitude = jTextField1.getText();
        String Latitude = jTextField2.getText();
        
        weibo4j.Place wp = new weibo4j.Place();
        wp.client.setToken("2.00IatpcDHJIpLD539d7e3848zYztqD");
        PoiidConverter PC = new PoiidConverter();
        UnicodeConverter UC = new UnicodeConverter();
        //开始搜索第一项微博所在经纬度的nearWeibo
        String GeoInfo2;
        try {
            
        GeoInfo2 = wp.nearbyWeiboSearch(parseFloat(Latitude), parseFloat(Longtitude));
        
        
        PC = new PoiidConverter();
        PC.converter(GeoInfo2, PC.Shiki_poiid);
        if(PC.POIIDs.size() == 0){
            new Frame_TenjiError().setVisible(true);
        }
        try{
        String UTFSearchResult = wp.placeWeiboSearch((PC.POIIDs).get(0));
        
        UC = new UnicodeConverter();
        String KanjiResult = UC.convert(UTFSearchResult);

        //继续split
        String[] KanjiResultArray = KanjiResult.split("poiid");
        int KanjiLength = KanjiResultArray.length;

        //用正则表达式读取分割好的KanjiResultArray[]里的screen_name字段
        Vector<String> ResultName2 = new Vector<>();
        for(int j = 0;j<KanjiLength;j++){
            PoiidConverter PC_name = new PoiidConverter();
            PC_name.converter(KanjiResultArray[j], PC_name.Shiki_name);
            ResultName2.add(PC_name.Kekka);
        }


        //用正则表达式读取分割好的KanjiResultArray[]里的text字段
        Vector<String> ResultText2 = new Vector<>();
        for(int k = 0;k<KanjiLength;k++){
            PoiidConverter PC_text = new PoiidConverter();
            PC_text.converter(KanjiResultArray[k], PC_text.Shiki_text);
            ResultText2.add(PC_text.Kekka);
        }

        //用正则表达式读取分割好的KanjiResultArray[]里的时间字段
        Vector<String> ResultTime2 = new Vector<>();
        for(int k = 0;k<KanjiLength;k++){
            PoiidConverter PC_time = new PoiidConverter();
            PC_time.converter(KanjiResultArray[k], PC_time.Shiki_time);
            ResultTime2.add(PC_time.Kekka);
        }
        WordFilter WF = new WordFilter();
        //去掉多余的符号
        WF = new WordFilter();
        RealName2 = WF.wordfilter(ResultName2, WF.FilterName,1,0);
        for(int j = RealName2.size();j<20;j++){
            RealName2.add("0");
        }
        WF = new WordFilter();
        RealTime2 = WF.wordfilter(ResultTime2, WF.FilterName,1,0);
        for(int j = RealTime2.size();j<20;j++){
            RealTime2.add("0");
        }
        WF = new WordFilter();
        RealText2 = WF.wordfilter(ResultText2, WF.FilterName,1,0);
        for(int j = RealText2.size();j<20;j++){
            RealText2.add("0");
        }


        //测试地理位置
        //nearSearcher新加段
        //用正则表达式读取分割好的KanjiResultArray[]里的lat，long字段
        Vector<String> ResultLong2 = new Vector<>();
        Vector<String> ResultLat2 = new Vector<>();
        for(int j = 0;j<KanjiLength;j++){
            PoiidConverter PC_long = new PoiidConverter();
            PoiidConverter PC_lat = new PoiidConverter();
            PC_long.converter(KanjiResultArray[j], PC_long.Shiki_long);
            ResultLong2.add(PC_long.Kekka);
            PC_lat.converter(KanjiResultArray[j], PC_lat.Shiki_lat);
            ResultLat2.add(PC_lat.Kekka);
        }

        //搞一下这个地方的名字
        PoiidConverter PC_name = new PoiidConverter();
        PC_name.converter(KanjiResultArray[2], PC_name.Shiki_placetitle);
        
        ResultNewPlaceName = PC_name.Kekka;
        System.out.println(ResultNewPlaceName);
        ResultNewPlaceName = ResultNewPlaceName.split("\".\"",4)[1];

        //取出lat，lon的纯数组部分
        //Vector<String> FloatLong2 = new Vector<>();
       // Vector<String> FloatLat2 = new Vector<>();
        WF = new WordFilter();
        FloatLong2 = WF.wordfilter(ResultLong2, WF.FilterLon,1,1);
        WF = new WordFilter();
        FloatLat2 = WF.wordfilter(ResultLat2, WF.FilterLat,1,1);
        //画个地图吧
        MapDraw MD2 = new MapDraw();
        MD2.urlMap(Longtitude, Latitude);
        }catch (WeiboException e) {
            new Frame_TenjiError().setVisible(true);
        }
        }catch (WeiboException e) {
                e.printStackTrace();
        }
        new Frame_Tenji2().setVisible(true);
        //System.out.println(ResultNewPlaceName);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Nyuryoku2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Nyuryoku2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Nyuryoku2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Nyuryoku2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Nyuryoku2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
