/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _geosearch;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.io.*;  
import java.net.MalformedURLException;  
import java.net.URL; 

/**
 *
 * @author luyimeng
 */
public class Frame_Tenji1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Tenji1
     */
    public Frame_Tenji1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
        jLabel1.setText(Frame_Nyuryoku1.getTitleTrans());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {Frame_Nyuryoku1.getNameTrans(0), Frame_Nyuryoku1.getTimeTrans(0),Frame_Nyuryoku1.getFloatLong(0) , Frame_Nyuryoku1.getFloatLat(0), Frame_Nyuryoku1.getTextTrans(0)},
                {Frame_Nyuryoku1.getNameTrans(1), Frame_Nyuryoku1.getTimeTrans(1),Frame_Nyuryoku1.getFloatLong(1) , Frame_Nyuryoku1.getFloatLat(1), Frame_Nyuryoku1.getTextTrans(1)},
                {Frame_Nyuryoku1.getNameTrans(2), Frame_Nyuryoku1.getTimeTrans(2),Frame_Nyuryoku1.getFloatLong(2) , Frame_Nyuryoku1.getFloatLat(2), Frame_Nyuryoku1.getTextTrans(2)},
                {Frame_Nyuryoku1.getNameTrans(3), Frame_Nyuryoku1.getTimeTrans(3),Frame_Nyuryoku1.getFloatLong(3) , Frame_Nyuryoku1.getFloatLat(3), Frame_Nyuryoku1.getTextTrans(3)},
                {Frame_Nyuryoku1.getNameTrans(4), Frame_Nyuryoku1.getTimeTrans(4),Frame_Nyuryoku1.getFloatLong(4) , Frame_Nyuryoku1.getFloatLat(4), Frame_Nyuryoku1.getTextTrans(4)},
                {Frame_Nyuryoku1.getNameTrans(5), Frame_Nyuryoku1.getTimeTrans(5),Frame_Nyuryoku1.getFloatLong(5) , Frame_Nyuryoku1.getFloatLat(5), Frame_Nyuryoku1.getTextTrans(5)},
                {Frame_Nyuryoku1.getNameTrans(6), Frame_Nyuryoku1.getTimeTrans(6),Frame_Nyuryoku1.getFloatLong(6) , Frame_Nyuryoku1.getFloatLat(6), Frame_Nyuryoku1.getTextTrans(6)},
                {Frame_Nyuryoku1.getNameTrans(7), Frame_Nyuryoku1.getTimeTrans(7),Frame_Nyuryoku1.getFloatLong(7) , Frame_Nyuryoku1.getFloatLat(7), Frame_Nyuryoku1.getTextTrans(7)},
                {Frame_Nyuryoku1.getNameTrans(8), Frame_Nyuryoku1.getTimeTrans(8),Frame_Nyuryoku1.getFloatLong(8) , Frame_Nyuryoku1.getFloatLat(8), Frame_Nyuryoku1.getTextTrans(8)},
                {Frame_Nyuryoku1.getNameTrans(9), Frame_Nyuryoku1.getTimeTrans(9),Frame_Nyuryoku1.getFloatLong(9) , Frame_Nyuryoku1.getFloatLat(9), Frame_Nyuryoku1.getTextTrans(9)},
                {Frame_Nyuryoku1.getNameTrans(10), Frame_Nyuryoku1.getTimeTrans(10),Frame_Nyuryoku1.getFloatLong(10) , Frame_Nyuryoku1.getFloatLat(10), Frame_Nyuryoku1.getTextTrans(10)},
                {Frame_Nyuryoku1.getNameTrans(11), Frame_Nyuryoku1.getTimeTrans(11),Frame_Nyuryoku1.getFloatLong(11) , Frame_Nyuryoku1.getFloatLat(11), Frame_Nyuryoku1.getTextTrans(11)},
                {Frame_Nyuryoku1.getNameTrans(12), Frame_Nyuryoku1.getTimeTrans(12),Frame_Nyuryoku1.getFloatLong(12) , Frame_Nyuryoku1.getFloatLat(12), Frame_Nyuryoku1.getTextTrans(12)},
                {Frame_Nyuryoku1.getNameTrans(13), Frame_Nyuryoku1.getTimeTrans(13),Frame_Nyuryoku1.getFloatLong(13) , Frame_Nyuryoku1.getFloatLat(13), Frame_Nyuryoku1.getTextTrans(13)},
                {Frame_Nyuryoku1.getNameTrans(14), Frame_Nyuryoku1.getTimeTrans(14),Frame_Nyuryoku1.getFloatLong(14) , Frame_Nyuryoku1.getFloatLat(14), Frame_Nyuryoku1.getTextTrans(14)},
                {Frame_Nyuryoku1.getNameTrans(15), Frame_Nyuryoku1.getTimeTrans(15),Frame_Nyuryoku1.getFloatLong(15) , Frame_Nyuryoku1.getFloatLat(15), Frame_Nyuryoku1.getTextTrans(15)},
                {Frame_Nyuryoku1.getNameTrans(16), Frame_Nyuryoku1.getTimeTrans(16),Frame_Nyuryoku1.getFloatLong(16) , Frame_Nyuryoku1.getFloatLat(16), Frame_Nyuryoku1.getTextTrans(16)},
                {Frame_Nyuryoku1.getNameTrans(17), Frame_Nyuryoku1.getTimeTrans(17),Frame_Nyuryoku1.getFloatLong(17) , Frame_Nyuryoku1.getFloatLat(17), Frame_Nyuryoku1.getTextTrans(17)},
                {Frame_Nyuryoku1.getNameTrans(18), Frame_Nyuryoku1.getTimeTrans(18),Frame_Nyuryoku1.getFloatLong(18) , Frame_Nyuryoku1.getFloatLat(18), Frame_Nyuryoku1.getTextTrans(18)},
                {Frame_Nyuryoku1.getNameTrans(19), Frame_Nyuryoku1.getTimeTrans(19),Frame_Nyuryoku1.getFloatLong(19) , Frame_Nyuryoku1.getFloatLat(19), Frame_Nyuryoku1.getTextTrans(19)}
            },
            new String [] {
                "用户名", "发布时间", "经度", "纬度", "内容"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setText("Le");
        /*
        try{
            String imgurl = MapDraw.getMapURL();
            URL url = new URL(imgurl);
            BufferedInputStream  in = new BufferedInputStream(url.openStream());
            File img = new File("img2.png");
            BufferedOutputStream out = new BufferedOutputStream(new FileOutputStream(img));
            byte[] buf = new byte[1024];
            while(in.read(buf) != -1){
                out.write(buf);
            }
            in.close();
            out.close();
        }catch (MalformedURLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        */
        String imgurl = MapDraw.getMapURL();
        URL url = null;
        try{
            url = new URL(imgurl);
        }catch (MalformedURLException e2) {
            e2.printStackTrace();
        }
        InputStream is = null;
        try {
            is = url.openStream();
        } catch (IOException e1) {
            e1.printStackTrace();
        }
        OutputStream os = null;
        File f = new File("img2.png");
        //f.mkdirs();
        try{
            os = new FileOutputStream(f);
            int bytesRead = 0;
            byte[] buffer = new byte[8192];
            while((bytesRead = is.read(buffer,0,8192))!=-1){
                os.write(buffer,0,bytesRead);
            }
        }catch(FileNotFoundException e){
        } catch (IOException e) {
            e.printStackTrace();
        }

        System.out.println("FINISH");
        try{
            ImageIcon icon = new ImageIcon("img2.png");
            jLabel2 = new JLabel(icon);
        }catch (Exception e){
            System.out.println("catch住");
            ImageIcon icon = new ImageIcon("Atlas_Logo_AW.png");
            jLabel2 = new JLabel(icon);
        }
        //jLabel2.setIcon(icon);
        //jLabel2.repaint();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(366, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Tenji1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Tenji1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
